chore: Upgrades `redux`
HathorNetwork/hathor-wallet pull request #595
Opened 2024-04-29 18:35 UTC by tuliomir

:construction: This PR is still in the testing phase

### Acceptance Criteria
- Upgrades the `Redux` dependency

### Security Checklist
- [X] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2024-04-30 16:20 UTC, andreabadesso approved these changes

2024-04-30 16:20 UTC, andreabadesso commented on src/store/index.js
> +import { configureStore } from "@reduxjs/toolkit";
```suggestion
import { configureStore } from '@reduxjs/toolkit';
```

2024-04-30 16:20 UTC, andreabadesso requested changes

2024-04-30 16:20 UTC, andreabadesso commented on package.json
> +    "@reduxjs/toolkit": "^2.1.0",
```suggestion
    "@reduxjs/toolkit": "2.1.0",
```

2024-04-30 16:24 UTC, tuliomir commented on src/store/index.js
> +import { configureStore } from "@reduxjs/toolkit";
Fixed on https://github.com/HathorNetwork/hathor-wallet/pull/595/commits/e4303a2011596adb302c3ab6bd62f29cfc990c90

2024-04-30 16:25 UTC, tuliomir commented on package.json
> +    "@reduxjs/toolkit": "^2.1.0",
Fixed on https://github.com/HathorNetwork/hathor-wallet/pull/595/commits/e4303a2011596adb302c3ab6bd62f29cfc990c90

2024-05-02 14:05 UTC, andreabadesso approved these changes

2024-05-02 16:16 UTC, alexruzenhack approved these changes

2024-05-02 16:17 UTC, merged